const en = {
  got: "får",
  get: "få",
  office: "kontor",
  hanging: "henger",
  very: "veldig",
  venter: "waiting",
  head: "hode / hodet / et hode",
  looklike: "ser ut",
  skitten: "dirty",
  story: "etasje",
  bad: "dårlig",
  yawn: "gjasper",
  toomuch: "for mye",
  toomany: "for mange",
  iwantto: "har lyst på",
  soon: "snart",
  time: "tid",
  wait: "vent",
  beautiful: "vakker",
  laugh: "le",
  previous: "forrige",
  last: "siste (the last thing)",
  yesterday: "går",
  lastyear: "fjor",
  funny: "morsomme",
  must: "må",
  should: "bør",
  want: "vil",
  exciting: "spennende",
  thirlling: "spennende",
  lookingforwardto: "gleder seg til",
  goingto: "kommer til å",
  pant: "bukse",
};

export default en;
