const nk = {
  får: "got",
  få: "get",
  kontor: "office",
  henger: "hanging",
  hanging: "henger",
  veldig: "very",
  waiting: "venter",
  hode: "head",
  serut: "look like",
  formye: "too much",
  formange: "too many",
  harlystpå: "I want to",
  gledersegtil: "looking forward to",
  kommertilå: "going to",
  dirty: "skitten",
  etasje: "story",
  dårlig: "bad",
  gjasper: "yawn",
  snart: "soon",
  tid: "time",
  vent: "wait",
  vakker: "beautiful",
  le: "laugh",
  forrige: "previous",
  siste: "the last thing",
  går: "yesterday",
  fjor: "last year",
  morsomme: "funny",
  må: "must",
  bør: "should",
  vil: "want",
  spennende: "exciting / thrilling",
  bukse: "trousers",
};

export default nk;
